# $FreeBSD$

PORTNAME=       motsognir
PORTVERSION=    1.0.3
CATEGORIES=     net
LICENSE=        GPLv3
MASTER_SITES=	SF/${PORTNAME}/v${PORTVERSION}

MAINTAINER=     mateusz@viste-family.net
COMMENT=        A full-featured gopher server without dependencies
.include <bsd.port.mk>
